# Dockerfile.arm64

FROM python:3.10-slim

# Install dependencies
RUN apt-get update && apt-get install -y \
    ffmpeg \
    git \
    wget \
    curl \
    build-essential \
    libsndfile1 \
    && rm -rf /var/lib/apt/lists/*

# Install PyTorch for ARM64 (check compatibility)
RUN pip install torch==2.1.0 torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu

# Copy files
WORKDIR /app
COPY . /app

RUN pip install "pip<24.1"
# Install Python requirements
RUN pip install -r requirements.txt

# Default command (you can adjust this based on your workflow)
CMD ["python", "infer-web.py", "--pycmd", "python3"]
